### ISSUE TITLE
Set errno when intercepting system calls

### ISSUE THREAD

**Issue by leauny** [GJDuck/e9syscall#2]
## Is it possible to set `errno` when intercepting system calls?

The `accept` system call in the following code requires errno for judgment. 
When using e9syscall, it seems that errno cannot be passed out, which will cause the error log to be continuously output.

```cpp
while (1) {
        struct sockaddr_storage in_addr;
        bzero(&in_addr, sizeof(in_addr));
        socklen_t in_len = sizeof(in_addr);
        butil::fd_guard in_fd(accept(acception->fd(), (sockaddr*)&in_addr, &in_len));
        if (in_fd < 0) {
            // no EINTR because listened fd is non-blocking.
            if (errno == EAGAIN) {
                return;
            }
            // Do NOT return -1 when `accept' failed, otherwise `_listened_fd'
            // will be closed. Continue to consume all the events until EAGAIN
            // instead.
            // If the accept was failed, the error may repeat constantly, 
            // limit frequency of logging.
            PLOG_EVERY_SECOND(ERROR)
                << "Fail to accept from listened_fd=" << acception->fd();
            continue;
        }
    ...
}
```

**Comment by leauny** [comment]
the addr of errno in intercepted libc is `0x7ffde5800680`, while in executable is `0x7ffde58002c0`。

**Comment by GJDuck** [comment]
The `errno` value can be set indirectly by setting the `result` to be the negation of the error.  E.g.:

        *result = -EAGAIN

This is how the kernel returns error codes.  Libc will then set the `errno` accordingly.
